run:
  timeout: 5m
linters:
  enable:
    - asciicheck
    - depguard
    - errorlint
    - gci
    - gochecknoinits
    - gofmt
    - goimports
    - gosec
    - megacheck
    - misspell
    - nakedret
    - nolintlint
    - predeclared
    - revive
    - unconvert
    - unparam
linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      - io/ioutil
    packages-with-error-message:
      - io/ioutil: "The 'io/ioutil' package is deprecated. Use corresponding 'os' or 'io' functions instead."
issues:
  exclude-rules:
  - linters:
    - gosec
    text:  "Implicit memory aliasing in for loop."
    path: _test\.go
  - linters:
    - revive
    text: "unexported-return"
  - linters:
    - revive
    text: "var-naming"
