run:
  timeout: 5m
linters:
  enable:
    - asciicheck
    - errorlint
    - gci
    - gochecknoinits
    - gofmt
    - goimports
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam
issues:
  exclude-rules:
  - linters:
    - gosec
    text:  "Implicit memory aliasing in for loop."
    path: _test\.go
  - linters:
    - revive
    text: "unexported-return"
  - linters:
    - revive
    text: "var-naming"
