run:
  timeout: 5m
linters:
  enable:
    - errorlint
    - gofmt
    - goimports
    - gosec
    - misspell
issues:
  exclude-rules:
  - linters:
    - gosec
    text:  "Implicit memory aliasing in for loop."
    path: _test\.go
