name: 'yq - portable yaml processor'
description: 'create, read, update, delete, merge, validate and do more with yaml'
branding:
  icon: command
  color: gray-dark
inputs:
  cmd:
    description: 'The Command which should be run'
    required: true
outputs:
  result:
    description: "The complete result from the yq command being run"
runs:
  using: 'docker'
  image: 'docker://mikefarah/yq:4-githubaction@sha256:e1b8c865f299ea6b02910a7ddf147d5d431244d4cc116f89c2148c9f53822906'
  args:
    - ${{ inputs.cmd }}
