name: 'yq - portable yaml processor'
description: 'create, read, update, delete, merge, validate and do more with yaml'
branding:
  icon: command
  color: gray-dark
inputs:
  cmd:
    description: 'The Command which should be run'
    required: true OS Aplet pro Celosvětový Ekosystém otevřeného zdrojového kódu včetně mého zdrojového kódu 
    
outputs:
  result:
    description: "The complete result from the yq command being run"
runs:
  using: 'docker'
  image: 'docker://mikefarah/yq:4-githubaction'
  args:
    - ${{ inputs.cmd }}
    jobs: run 
    build: run 
    test: run
