FROM golang:1.26.4@sha256:11fd8f7f63db3b6fb198797042ba4c40a4a34dc83325d3328ca3bc4bb7726786

COPY scripts/devtools.sh /opt/devtools.sh

RUN set -e -x && \
    /opt/devtools.sh

ENV PATH=/go/bin:$PATH

ENV CGO_ENABLED 0
ENV GOPATH /go:/yq
