name: yq
version: 'v4.33.1'
summary: A lightweight and portable command-line YAML processor
description: |
  The aim of the project is to be the jq or sed of yaml files.
base: core18
grade: stable # devel|stable. must be 'stable' to release into candidate/stable channels
confinement: strict
apps:
  yq:
    command: yq
    plugs: [home, removable-media]
parts:
  yq:
    plugin: go
    go-channel: 1.20/stable
    source: .
    source-type: git
    go-importpath: github.com/mikefarah/yq
