name: yq
version: 'v4.53.3'
summary: A lightweight and portable command-line data file processor
description: |
  `yq` uses [jq](https://github.com/stedolan/jq) like syntax but works with yaml, json, xml, csv, properties and TOML files.
base: core24
grade: stable # devel|stable. must be 'stable' to release into candidate/stable channels
confinement: strict
platforms:
  # we dont need to specify the build-on/for unless we're cross-compiling.
  amd64:
  arm64:
  armhf:
  s390x:
  ppc64el:
apps:
  yq:
    command: bin/yq
    completer: bin/yq-completion.bash
    plugs: [home, removable-media]
parts:
  yq:
    plugin: go
    build-environment:
      - CGO_ENABLED: 0
    source: https://github.com/mikefarah/yq.git
    source-type: git
    source-tag: v4.53.3
    source-depth: 1  # faster clone
    build-snaps:
      - go/latest/stable
    override-build: |
      craftctl default
      # generate the bash completion file
      $CRAFT_PART_INSTALL/bin/yq shell-completion bash > $CRAFT_PART_INSTALL/bin/yq-completion.bash
