name: yq
version: 'v4.48.1'
summary: A lightweight and portable command-line data file processor
description: |
  `yq` uses [jq](https://github.com/stedolan/jq) like syntax but works with yaml, json, xml, csv, properties and TOML files.
base: core22
grade: stable # devel|stable. must be 'stable' to release into candidate/stable channels
confinement: strict
architectures:
  - build-on: [amd64]
    build-for: [all]
# architectures:
#   - build-on: s390x
#   - build-on: ppc64el
#   - build-on: arm64
#   - build-on: armhf
#   - build-on: amd64
#   - build-on: i386
#   - build-on: riscv64
apps:
  yq:
    command: bin/yq
    plugs: [home, removable-media]
parts:
  yq:
    plugin: go
    build-environment:
      - CGO_ENABLED: 0
    source: https://github.com/mikefarah/yq.git
    source-tag: v4.48.1
    build-snaps:
      - go/latest/stable
