name: yq
version: 'v4.40.5'
summary: A lightweight and portable command-line data file processor
description: |
  `yq` uses [jq](https://github.com/stedolan/jq) like syntax but works with yaml, json, xml, csv, properties and TOML files.
base: core22
grade: stable # devel|stable. must be 'stable' to release into candidate/stable channels
confinement: strict
apps:
  yq:
    command: bin/yq
    plugs: [home, removable-media]
parts:
  yq:
    plugin: go
    source: .
    build-snaps:
      - go/1.20/stable
